ZOOMLEVELS:
    0: [0, 1]
    1: [1, 2]
    2: [2, 4]
    3: [4, 8]
    4: [8, 16]
    5: [16, 32]
    6: [32, 64]
    7: [64, 128]
    8: [128, 256]
    9: [256, 512]
    10: [512, 1024]
    11: [1024, 2048]
    12: [2048, 4096]
    13: [4096, 8192]
    14: [8192, 16384]
    15: [16384, 32768]
    16: [32768, 65536]
    17: [65536, 9999999999999]
    
MAP_BACKGROUND: 0.94 0.93 0.90
SEA_COLOR: 0.67 0.79 0.89

#: see http://wiki.openstreetmap.org/wiki/Key:TAGNAME
POINT:
    place:
        city:
            - 3-14:
                text: name
                text-color: 0 0 0
                font-size: 9
                font-weight: bold
                text-halo-color: 1 1 1 0.88
                text-halo-width: 1.5
                z-index: 99
            - 6-10:
                font-size: 9
            - 3-5:
                font-size: 10
        town:
            - 0-10:
                text: name
                text-color: 0.1 0.1 0.1
                font-size: 8
                text-halo-color: 1 1 1 0.88
                text-halo-width: 1.5
                z-index: 98
            - 4-6:
                font-weight: bold
            - 1-3:
                text-color: 0.1 0.1 0.1
                font-size: 10
                font-weight: bold
                z-index: 98
        suburb:
            - 1-5:
                text: name
                text-color: 0.5 0.5 0.5
                font-size: 8
                font-weight: bold
                text-halo-color: 1 1 1 0.88
                text-halo-width: 1.5
            - 0-2:
                font-size: 9
                text-transform: uppercase
            - 0, 1:
                font-size: 10
        village:
            - 0-6:
                text: name
                text-color: 0.5 0.5 0.5
                text-halo-color: 1 1 1 0.88
                text-halo-width: 1.5
                font-size: 8
                font-weight: bold
            - 2:
                font-size: 9
            - 0, 1:
                font-size: 10
        hamlet, isolated_dwelling, farm, locality:
            - 0-3:
                text: name
                text-color: 0.5 0.5 0.5
                text-halo-color: 1 1 1 0.88
                text-halo-width: 1.5
                font-size: 8
                font-weight: bold
            - 2:
                font-size: 9
            - 0, 1:
                font-size: 10
        island:
            - 0-3:
                text: name
                text-color: 0.2 0.2 0.2
                text-halo-color: 1 1 1 0.88
                text-halo-width: 1.5
                font-size: 8
                z-index: 93
        islet:
            - 0, 1, 2:
                text: name
                text-color: 0.2 0.2 0.2
                text-halo-color: 1 1 1 0.88
                text-halo-width: 1.5
                font-size: 7
                z-index: 92
                
                
LINE:
    highway: 
        motorway:
            - all:
                color: 1 0.88 0.29
                width: 1
                border-width: 1
                border-color: 0.89 0.31 0.31
                outline-width: 0.7
                outline-color: 0.67 0.32 0.4
                z-index: 99
            - 6, 7:
                width: 1
                border-width: 1.5
                outline-width: 0.7
            - 3-5:
                width: 1.5
                border-width: 1.5
                outline-width: 1
            - 0-2:
                width: 1.5
                border-width: 2
                outline-width: 2
        motorway_link:
            - 0-7:
                color: 0.89 0.31 0.31
                width: 1
                border-width: 1
                border-color: 0.67 0.32 0.4
                z-index: 95
            - 2-7:
                width: 1.5
                border-width: 1
            - 0, 1:
                width: 6
                border-width: 1
        trunk, trunk_link:
            - 0-9:
                color: 0.88 0.65 0.65
                width: 1
                border-width: 0.7
                border-color: 0.68 0.34 0.34
                z-index: 98
            - 7:
                width: 1.5
                border-width: 0.8
            - 4-6:
                width: 2
                border-width: 1
            - 0-3:
                width: 3
            - 0-4:
                font-size: 8
                text: name
                text-color: 0.15 0.15 0.15
                text-halo-width: 1
                text-halo-color: 1 1 1 0.8
            - 0, 1:
                font-size: 10
                width: 7
                border-width: 1.5
            - 0:
                width: 11.5
        primary, primary_link:
            - 0-9:
                color: 0.98 0.88 0.58
                width: 1
                border-color: 0.8 0.57 0.12
                border-width: 0.7
                z-index: 97
            - 7:
                width: 1.5
                border-width: 0.7
            - 4-6:
                width: 2
                border-width: 1
            - 0-3:
                width: 3
            - 0-4:
                font-size: 8
                text: name
                text-color: 0.15 0.15 0.15
                text-halo-width: 1
                text-halo-color: 1 1 1 0.8
            - 0, 1:
                font-size: 10
                width: 7
                border-width: 1.5
            - 0:
                width: 6
        secondary, secondary_link:
            - 0-9:
                color: 0.74 0.74 0.74
                width: 1
                z-index: 95
            - 0-6:
                color: 1 1 1
                width: 1.5
                border-color: 0.74 0.74 0.74
                border-width: 0.7
            - 0-4:
                font-size: 8
                text: name
                text-color: 0.15 0.15 0.15
                text-halo-width: 1
                text-halo-color: 1 1 1 0.8
            - 0-3:
                width: 3
                border-width: 1
            - 0, 1:
                font-size: 10
                width: 4
                border-width: 1.5
            - 0:
                width: 6
        tertiary:
            - 0-6:
                color: 0.87 0.87 0.83
                width: 1
                z-index: 95
            - 0-3:
                width: 1.5
                text: name
                text-color: 0.15 0.15 0.15
                text-halo-width: 1
                text-halo-color: 1 1 1 0.8
                font-size: 8
                color: 1 1 1
                border-width: 1
                border-color: 0.74 0.74 0.74
            - 2:
                z-index: 95
            - 0, 1:
                font-size: 10
                width: 4
                border-width: 1.5
            - 0:
                width: 6
        unclassified, road:
            - 0-6:
                color: 0.87 0.87 0.83
                width: 1
                z-index: 94
            - 0-3:
                width: 1.5
                color: 1 1 1
                border-width: 1
                border-color: 0.74 0.74 0.74
                z-index: 95
            - 0-2:
                font-size: 8
                text: name
                text-color: 0.15 0.15 0.15
                text-halo-width: 1
                text-halo-color: 1 1 1 0.8
            - 0, 1:
                width: 4
                border-width: 1.5
                font-size: 10
            - 0:
                width: 6
        residential, living_street, service:
            - 0-6:
                color: 0.87 0.87 0.83
                width: 1
                z-index: 94
            - 0-3:
                color: 1 1 1
                width: 1.5
                border-color: 0.74 0.74 0.74
                border-width: 1
                z-index: 95
            - 0-2:
                font-size: 8
                text: name
                text-color: 0.15 0.15 0.15
                text-halo-width: 1
                text-halo-color: 1 1 1 0.8
            - 0, 1:
                width: 4
                border-width: 1.5
                font-size: 10
            - 0:
                width: 6
        track, pedestrian, raceway, services, bus_guidewaypath, cycleway, footway, bridleway, steps:
            - 0-3:
                color: 0.8 0.8 0.8
                width: 1
                border-color: 0.74 0.74 0.74
                z-index: 94
            - 0-2:
                color: 1 1 1
                border-width: 0.7
                z-index: 95
            - 0, 1:
                width: 2
                border-width: 1
                font-size: 9
                text: name
                text-color: 0.15 0.15 0.15
                text-halo-width: 1
                text-halo-color: 1 1 1 0.8
            - 0:
                width: 3
                
    railway:
        rail:
            - all:
                color: 0.66 0.66 0.66
                width: 1
                line-dash: 1
                line-cap: butt
                z-index: 1
            - 0, 1:
                color: 1 1 1
                width: 1
                line-dash: 3
                border-width: 0.7
                border-color: 0.5 0.5 0.5
            
    waterway:
        river:
            - all:
                color: 0.67 0.79 0.89
                width: 1.5
                z-index: 0
            - 0-4:
                width: 2
                font-size: 8
                font-style: italic
                text: name
                text-color: 0.23 0.38 0.51
                text-halo-width: 1
                text-halo-color: 1 1 1 0.7
            - 0, 1:
                width: 4
                font-size: 9
        stream:
            - 0-5:
                color: 0.67 0.79 0.89
                width: 1
                z-index: 0
            - 0, 1:
                width: 2
                font-size: 9
                font-style: italic
                text: name
                text-color: 0.23 0.38 0.51
                text-halo-width: 1
                text-halo-color: 1 1 1 0.7
                
    boundary:
        administrative[admin_level=1]:
            - all:
                color: 0.5 0.5 0.5
                width: 1.5
                line-dash: 6 12
                border-width: 1
                border-color: 1 0.99 0.54
        administrative[admin_level=2]:
            - 0-9:
                color: 0.5 0.5 0.5
                width: 1.5
                line-dash: 6 12
                
    aeroway:
        runway:
            - 0-6:
                color: 0.74 0.74 0.74
                width: 1
                z-index: 92
            - 0-3:
                width: 2
        taxiway:
            - 0-6:
                color: 0.74 0.74 0.74
                width: 1
                z-index: 92
            - 0-3:
                width: 2
                
POLYGON:
    building:
        yes:
            - 0-3:
                background-color: 0.87 0.86 0.83
                z-index: 99
            - 0:
                text: addr_housenumber
    landuse:
        allotments, brownfield, cemetery, commercial, construction, garages: &landuse_default
            - 0, 1, 2:
                background-color: 0.9 0.9 0.9
        greenfield, greenhouse_horticulture, industrial, landfill, meadow: *landuse_default
        orchard, plant_nursery, quarry, railway: *landuse_default
        retail, salt_pond, vineyard: *landuse_default
        basin:
            - all:
                background-color: 0.67 0.79 0.89
        farm, farmland, grass:
            - 0, 1:
                background-color: 0.95 0.88 0.82
        farmyard:
            - 0, 1:
                background-color: 0.95 0.88 0.82
        forest:
            - all:
                background-color: 0.76 0.89 0.73
        military:
            - all:
                background-color: 0.89 0.89 0.79
        residential:
            - 0, 1, 2:
                background-color: 0.94 0.94 0.9
        village_green, recreation_ground:
            - all:
                background-color: 0.7 0.8 0.6
            
    leisure:
        sports_centre, golf_course, stadium, track, pitch:
            - all:
                background-color: 0.59 0.89 0.79
        nature_reserve, park, garden, common:
            - all:
                background-color: 0.82 0.89 0.82
            
    natural:
        beach:
            - all:
                background-color: 0.9 0.9 0.9
        heath, land, mud, scrub, wetland:
            - all:
                background-color: 0.89 0.89 0.79
        water:
            - all:
                background-color: 0.67 0.79 0.89
        glacier:
            - all:
                background-color: 0.95 0.95 0.95
        wood:
            - all:
                background-color: 0.80 0.89 0.72
                
    waterway:
        riverbank:
            - all:
                background-color: 0.67 0.79 0.89
                z-index: 98
            
